### ISSUE TITLE
Write installation instruction

### ISSUE THREAD

**Issue by giangm9** [SafeStudio/unofficial-zalo#1]
Need a installation guilde for the program ( build from source and get the .deb file)

**Comment by TsuKpa** [comment]
Need features application running background (sorry my bad English).

**Comment by ansidev** [comment]
@TsuKpa: I created new issue [Background mode for application](https://github.com/SafeStudio/unofficial-zalo/issues/2) for you. Please create new issue instead of comment in unrelated issue.

**Comment by ansidev** [comment]
I solved this issue.
