### ISSUE TITLE
Help me to build app!

### ISSUE THREAD

**Issue by TsuKpa** [SafeStudio/unofficial-zalo#3]
Need help when i build in terminal. 
Some error when i excute first command in README.md : 
> npm install -g electron electron-packager electron-installer-debian

Screenshot:
https://drive.google.com/file/d/0Bz7IVcNfHmNTSlZtTDhmSkZ0OFU/view?usp=sharing
https://drive.google.com/file/d/0Bz7IVcNfHmNTeXNFVi1wbk1rTGs/view?usp=sharing

**Comment by ansidev** [comment]
@TsuKpa:
- Required node version is `>=4.6`, yours is `4.2`.
- I'm sorry, for Windows, you don't need to install `electron-installer-debian`. It is used to package release build to Debian package.

**Comment by ansidev** [comment]
@TsuKpa: Can you build app? Please feedback, so I can close this issue.
