### ISSUE TITLE
Window starting app without build (confirmed)

### ISSUE THREAD

**Issue by hUwUtao** [SafeStudio/unofficial-zalo#36]
i found it, windows possible to run this app without builld. My step on powershell, cmd is

1, Mount at project (`cd`)
2,  `npm i`
3, `node_modules/electron/dist/electron.exe .`
The app now is excutable

You must fix the caption in readme.md : `don't support Windows`. You also must add the git line, cd, to clone this repo easily

**Comment by ansidev** [comment]
@pandaboy1942  Thank you for your feedback.

1. I don't support Windows mean that I won't support resolving any problem while use this app/source code on Windows OS. But Electron is a cross platform so you can make it works on Windows. Feel free to fork this repository and make changes, then create a pull request and I will review and merge it.
2. The way you are using to run this app on Windows is only suitable for development purpose.
